---
type: docker
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:8.0.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: test-node-14
  image: livingdocs/node:14
  commands: ["npm ci", "npm run test -s"]

- name: test-node-16
  image: node:16-alpine
  commands: ["rm -Rf node_modules", "npm ci", "npm run test -s"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 4eb7d63ca8826a5001d9d0136c3eee5fcf0ffc91b4faa00410ff908f6023a41a

...
