---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: eslint
  image: marcbachmann/eslint:4.19.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

- name: test-node-10
  image: node:10-alpine
  commands: ["npm ci", "npm run test -s"]

- name: test-node-12
  image: node:12-alpine
  commands: ["rm -Rf node_modules", "npm ci", "npm run test -s"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: ea6dec4cbe6f6221d3b5b938721f4872f28761cefe9edaf63a353aa1ae6d8da2

...
